mememe_app/config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources :users do
    resources :images do
      resources :captions
    end
    resources :captions
  end

  resources :categories do
    resources :images do
      resources :captions
    end
  end

  resources :sessions, except: :destroy
  delete '/logout' => 'sessions#destroy'

  post '/categories/:category_id/images/:image_id/captions/:id/upvote' => 'captions#upvote'
  get '/categories/:category_id/images/:image_id/captions/:id/upvote' => 'captions#upvote'

  get 'welcome/loginerror' => 'welcome#loginerror'

end

mememe_app/app/models/caption.rb
class Caption < ActiveRecord::Base
  belongs_to :image
  belongs_to :user
  acts_as_votable
end

mememe_app/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :images
end

mememe_app/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :captions
end

mememe_app/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: true,
                       length: { minimum: 3 }
  validates :password, presence: true


  has_secure_password

  has_many :images
  has_many :captions
  acts_as_voter

end

mememe_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method(:current_user)

  def authorize
    redirect_to root_path unless @current_user
  end

end

mememe_app/app/controllers/captions_controller.rb
class CaptionsController < ApplicationController

  def index
  end

  def create
    @caption = Caption.new(caption_params)
    @caption.image_id = params[:image_id]
    @caption.user_id = params[:user_id]
    @caption.save
    redirect_to category_image_path(params[:category_id], params[:image_id])
  end

  def upvote
    @caption = Caption.find(params[:id])
    @caption.liked_by current_user
    redirect_to :back
  end


  def caption_params
    params.require(:caption).permit(:text)
  end

end

mememe_app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @image = Image.new
    @image.category_id = @image.id
    @caption = Caption.new
    @caption.category_id = @caption.id
  end





end

mememe_app/app/controllers/images_controller.rb
class ImagesController < ApplicationController


  def index
    @images = Image.all
    @category = Category.find(params[:category_id])
  end

  def show
    @image = Image.find(params[:id])
    @category = Category.find(params[:category_id])
    @caption = Caption.new
    @caption.image_id = @image.id

    @likeNumbers = []
    @image.captions.each do |caption|
      @likeNumbers.push(caption.votes_for.size)
    end
    @mostLikes = @likeNumbers.max

    @image.captions.each do |cap|
      if cap.votes_for.size >= @mostLikes
        @topMeme = cap.text
      end
    end
  end
  

  def new
    @category = Category.find(params[:category_id])
    @image = Image.new
  end

  def create
    @category = Category.find(params[:category_id])
    @image = Image.new(image_params)
    @image.user_id = params[:user_id]
    @image.category_id = params[:category_id]
    @image.save
    redirect_to category_image_path(@category.id, @image.id)
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    flash.notice = "The '#{@image.title}' is Gone!"
    redirect_to category_images_path
  end

  def image_params
    params.require(:image).permit(:title, :photo_url)
  end


end

mememe_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to welcome_loginerror_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end


end

mememe_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :authorize, except: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @image = Image.new
    @image.user_id = @image.id
    @caption = Caption.new
    @caption.user_id = @caption.id
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    puts user_params
    if user.save
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to root_path
  end
end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :password,
      :password_confirmation
    )
  end


end

mememe_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

  def loginerror
  end

end

mememe_app/app/helpers/application_helper.rb
module ApplicationHelper
end

mememe_app/app/views/categories/index.html.erb
<div class="category_index">
<h1>Choose an Image Category</h1>
<br>
<ul>
  <div class="btn-group-vertical" role="group" aria-label="...">
    <% @categories.each do |category| %>
      <button type="button" class="btn btn-default btn-lg"><%= link_to category.name, category_images_path(category) %></button>
    <% end %>
  </div>
</ul>
</div>

mememe_app/app/views/images/_comment.html.erb
<p><%= comment.text %></p>

mememe_app/app/views/images/_form.html.erb
<h2>Put Your Caption Here</h2>
<%= form_for @caption, url: category_image_captions_path do |f| %>
<p>
  <%= f.label :text, "right here" %>
  <%= f.text_field :text %>
</p>
<p>
<%= f.submit "Captionize" %>
</p>
<% end %>

mememe_app/app/views/images/index.html.erb
<div class="image_index">
<h1>Welcome to <%= @category.name %> Images</h1>
<button class="btn btn-lg"><%= link_to 'Post a Potential ' + @category.name + ' Meme', new_category_image_path %></button><br>

<ul>
  <% @category.images.each do |image| %>
    <li>
      <h4 id="image-title"><%= link_to image.title, category_image_path(@category.id, image) %></h4>
      <img src= "<%= image.photo_url %>" alt="<%= image.title %>" />
    </li>
    <% end %>
</ul>

</div>

<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default"><%= link_to 'Back to Categories', categories_path %></button>
  <button type="button" class="btn btn-default"><%= link_to 'HOME', root_path %></button>
</div>

mememe_app/app/views/images/new.html.erb
<div class="image_new">
<h1>The Path to Meme Starts Here</h1>
<%= form_for(@image, url: category_images_path(@category.id)) do |f| %>
  <ul>
    <% @image.errors.full_messages.each do |error| %>
      <li><%= error %></li>
      <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :photo_url %><br />
    <%= f.text_area :photo_url %>
  </p>
  <p>
    <%# f.select :category, options_for_select (%w[Animals Babies Nerds Landscape Idiots Celebrities Other]) %>
  </p>
  <p>
    <%= f.submit 'memeME' %>
  </p>
  <% end %>
</div>
<%= link_to 'HOME', root_path %>

mememe_app/app/views/images/show.html.erb
<div class="image_show">
  
<h1> <%= @image.title %> </h1>
<h5><%= @category.name %></h5><br>

<div id="image">
  <img src= "<%= @image.photo_url %>" alt="<%= @image.title %>" />
  <h2><%= @topMeme.upcase %></h2>
</div>

<br>

<h2>Meme Creator</h2>
<!-- form to create image captions -->
<%= form_for @caption, url: category_image_captions_path(@category.id, @image) do |f| %>
 <%= f.text_field :text %>
 <%= f.submit "post" %>
 <% end%>

<h2>The Memes</h2>
<!-- render image captions -->
<ul id="image-captions" class="list-group">

 <% @image.captions.each do |caption| %>
 <li class="list-group-item">
 <%= caption.text %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 <button class="like"><%= link_to 'LIKE', "/categories/#{@category.id}/images/#{@image.id}/captions/#{caption.id}/upvote" %></button> &nbsp;<%= caption.votes_for.size %>
 </li>
 <% end %>
 </ul>

 </div>

 <div id="foot-nav" class="btn-group" role="group" aria-label="...">
   <button type="button" class="btn btn-default"><%= link_to 'Back to Categories', categories_path %></button>
   <button type="button" class="btn btn-default"><%= link_to 'HOME', root_path %></button>
   <button type="button" class="btn btn-default"><%= link_to 'Delete Image', category_image_path(@category.id, @image.id), method: :delete %></button>
 </div>

mememe_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MememeApp</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">
          <img id="logo" src="<%= asset_path('mememe-logo.png') %>" alt="mememe">
        </a>
      </div>
      <ul id="nav-links" class="nav navbar-nav">
        <% if current_user %>
        <li id="nav-welcome" class="navbar-brand"><%= current_user.username %> logged in</li>
        <li class="navbar-brand"><%= link_to 'logout', logout_path, method: :delete %></li>
        <% else %>
        <li class="navbar-brand"><%= link_to 'LOGIN', new_session_path %></li>
        <li class="navbar-brand"><%= link_to 'SIGN UP', new_user_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

<div id="content">

<%= yield %>

</div>

</body>
</html>

mememe_app/app/views/users/index.html.erb
<h1>Browse Your Favorite Users</h1>

<ul>
  <% @users.each do |user| %>
  <li>
    <%= link_to user.username, user_path(user) %>
  </li>
  <% end %>
</ul>

<%= link_to 'HOME', root_path %>

mememe_app/app/views/users/new.html.erb
<div id="new-user">
  <h1>Sign Up!</h1>
  <h2>Take memeME for all it's worth</h2>
    <%= bootstrap_form_for(@user, layout: :horizontal) do |f| %>
      <%= f.text_field :username, placeholder: "Choose a Username...", icon: "user" %>
      <%= f.password_field :password, placeholder: "Choose a Password..."%>
      <%= f.password_field :password_confirmation, label: "Confirm Password", placeholder: "Confirm Password..." %>
      <%= f.submit "Sign Up" %>
    <% end %>
</div>
<br>

<%= link_to 'HOME', root_path %>

mememe_app/app/views/users/show.html.erb
<%= @user.username %>


<%= link_to 'HOME', root_path %>
<%= link_to 'Browse Users', users_path %>

mememe_app/app/views/welcome/index.html.erb
<div class="home_page">
  <div id="home-container" class="well">
<h1>memeME: the social meme creator</h1>
<% if current_user %>
<h4>Hey, <%= current_user.username %></h4><br>
<p><%= link_to 'logout', logout_path, method: :delete %>
<% else %>
<ul>
  <li>
    <p class="btn btn-default"><%= link_to 'LOGIN', new_session_path %></p>
  </li>
  <li>
    <p class="btn btn-default"><%= link_to 'SIGN UP', new_user_path %></p>
  </li>
</ul>
<% end %>
<br>
<p id="category-butt" class="btn btn-default"><%= link_to 'BROWSE CATEGORIES', categories_path %></p>
  </div>
</div>

mememe_app/app/views/welcome/loginerror.html.erb
<h2>Incorrect Login Info!</h2>
<h3><%= link_to 'Sign up', new_user_path %> for an account</h3><br>
<br>
<h5>or <%= link_to 'get outta here', url:(www.google.com) %></h5>